export interface Verse {
  ref: string
  text: string
}

export const VERSES: Verse[] = [
  { ref: 'John 3:16', text: 'For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.' },
  { ref: 'Philippians 4:13', text: 'I can do all this through him who gives me strength.' },
  { ref: 'Psalm 23:1', text: 'The Lord is my shepherd, I lack nothing.' },
  { ref: 'Jeremiah 29:11', text: 'For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.' },
  { ref: 'Romans 8:28', text: 'And we know that in all things God works for the good of those who love him, who have been called according to his purpose.' },
  { ref: 'Proverbs 3:5-6', text: 'Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.' },
  { ref: 'Isaiah 40:31', text: 'But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.' },
  { ref: 'Matthew 11:28', text: 'Come to me, all you who are weary and burdened, and I will give you rest.' },
  { ref: 'Psalm 46:1', text: 'God is our refuge and strength, an ever-present help in trouble.' },
  { ref: 'Romans 8:38-39', text: 'For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.' },
  { ref: 'Joshua 1:9', text: 'Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.' },
  { ref: 'Psalm 121:1-2', text: 'I lift up my eyes to the mountains — where does my help come from? My help comes from the Lord, the Maker of heaven and earth.' },
  { ref: 'Matthew 6:33', text: 'But seek first his kingdom and his righteousness, and all these things will be given to you as well.' },
  { ref: 'Galatians 5:22-23', text: 'But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law.' },
  { ref: '1 Corinthians 13:4-5', text: 'Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs.' },
  { ref: 'Psalm 119:105', text: 'Your word is a lamp for my feet, a light on my path.' },
  { ref: 'John 14:6', text: 'Jesus answered, I am the way and the truth and the life. No one comes to the Father except through me.' },
  { ref: 'Isaiah 41:10', text: 'So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.' },
  { ref: 'Psalm 37:4', text: 'Take delight in the Lord, and he will give you the desires of your heart.' },
  { ref: '2 Timothy 1:7', text: 'For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.' },
  { ref: 'Ephesians 2:8-9', text: 'For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God — not by works, so that no one can boast.' },
  { ref: 'John 16:33', text: 'I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.' },
  { ref: 'Psalm 28:7', text: 'The Lord is my strength and my shield; my heart trusts in him, and he helps me. My heart leaps for joy, and with my song I praise him.' },
  { ref: 'Matthew 5:9', text: 'Blessed are the peacemakers, for they will be called children of God.' },
  { ref: 'Proverbs 31:25', text: 'She is clothed with strength and dignity; she can laugh at the days to come.' },
  { ref: 'Romans 15:13', text: 'May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit.' },
  { ref: 'Psalm 91:1-2', text: 'Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty. I will say of the Lord: He is my refuge and my fortress, my God, in whom I trust.' },
  { ref: 'John 15:13', text: 'Greater love has no one than this: to lay down one\'s life for one\'s friends.' },
  { ref: 'Matthew 5:44', text: 'But I tell you, love your enemies and pray for those who persecute you.' },
  { ref: 'Revelation 21:4', text: 'He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away.' },
  { ref: 'Psalm 23:4', text: 'Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.' },
  { ref: 'James 1:2-3', text: 'Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.' },
  { ref: 'Isaiah 26:3', text: 'You will keep in perfect peace those whose minds are steadfast, because they trust in you.' },
  { ref: 'Lamentations 3:22-23', text: 'Because of the Lord\'s great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.' },
  { ref: '1 Peter 5:7', text: 'Cast all your anxiety on him because he cares for you.' },
  { ref: 'Zephaniah 3:17', text: 'The Lord your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.' },
  { ref: 'Proverbs 22:6', text: 'Start children off on the way they should go, and even when they are old they will not turn from it.' },
  { ref: 'Hebrews 11:1', text: 'Now faith is confidence in what we hope for and assurance about what we do not see.' },
  { ref: 'Matthew 28:19-20', text: 'Therefore go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, and teaching them to obey everything I have commanded you. And surely I am with you always, to the very end of the age.' },
  { ref: 'Proverbs 4:23', text: 'Above all else, guard your heart, for everything you do flows from it.' },
  { ref: 'John 10:10', text: 'The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full.' },
  { ref: 'Micah 6:8', text: 'He has shown you, O mortal, what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God.' },
  { ref: 'Philippians 4:6-7', text: 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.' },
  { ref: 'Romans 12:2', text: 'Do not conform to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God\'s will is — his good, pleasing and perfect will.' },
  { ref: 'Ephesians 6:10', text: 'Finally, be strong in the Lord and in his mighty power.' },
  { ref: 'Colossians 3:23', text: 'Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.' },
  { ref: 'Psalm 139:14', text: 'I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well.' },
  { ref: 'Luke 6:31', text: 'Do to others as you would have them do to you.' },
  { ref: 'Psalm 27:1', text: 'The Lord is my light and my salvation — whom shall I fear? The Lord is the stronghold of my life — of whom shall I be afraid?' },
  { ref: '1 John 4:19', text: 'We love because he first loved us.' },
  { ref: 'John 8:32', text: 'Then you will know the truth, and the truth will set you free.' },
  { ref: 'John 8:32', text: 'Then you will know the truth, and the truth will set you free.' },
  { ref: 'Genesis 1:1', text: 'In the beginning God created the heavens and the earth.' },
  { ref: 'Psalm 1:1-2', text: 'Blessed is the one who does not walk in step with the wicked or stand in the way that sinners take or sit in the company of mockers, but whose delight is in the law of the Lord, and who meditates on his law day and night.' },
  { ref: 'Proverbs 1:7', text: 'The fear of the Lord is the beginning of wisdom, but fools despise wisdom and instruction.' },
  { ref: 'Isaiah 9:6', text: 'For to us a child is born, to us a son is given, and the government will be on his shoulders. And he will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace.' },
  { ref: 'Matthew 5:3', text: 'Blessed are the poor in spirit, for theirs is the kingdom of heaven.' },
  { ref: 'Matthew 5:4', text: 'Blessed are those who mourn, for they will be comforted.' },
  { ref: 'Matthew 5:5', text: 'Blessed are the meek, for they will inherit the earth.' },
  { ref: 'Matthew 5:6', text: 'Blessed are those who hunger and thirst for righteousness, for they will be filled.' },
  { ref: 'Matthew 5:7', text: 'Blessed are the merciful, for they will be shown mercy.' },
  { ref: 'Matthew 5:8', text: 'Blessed are the pure in heart, for they will see God.' },
  { ref: 'Matthew 6:9-10', text: 'Our Father in heaven, hallowed be your name, your kingdom come, your will be done, on earth as it is in heaven.' },
  { ref: 'Matthew 7:7', text: 'Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.' },
  { ref: 'Matthew 22:37-39', text: 'Love the Lord your God with all your heart and with all your soul and with all your mind. This is the first and greatest commandment. And the second is like it: Love your neighbor as yourself.' },
  { ref: 'Luke 1:37', text: 'For nothing is impossible with God.' },
  { ref: 'John 1:1', text: 'In the beginning was the Word, and the Word was with God, and the Word was God.' },
  { ref: 'John 11:25', text: 'Jesus said to her, I am the resurrection and the life. The one who believes in me will live, even though they die.' },
  { ref: 'John 13:34', text: 'A new command I give you: Love one another. As I have loved you, so you must love one another.' },
  { ref: 'John 14:1', text: 'Do not let your hearts be troubled. You believe in God; believe also in me.' },
  { ref: 'John 14:27', text: 'Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.' },
  { ref: 'Acts 1:8', text: 'But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth.' },
  { ref: 'Romans 1:16', text: 'For I am not ashamed of the gospel, because it is the power of God that brings salvation to everyone who believes.' },
  { ref: 'Romans 3:23', text: 'For all have sinned and fall short of the glory of God.' },
  { ref: 'Romans 5:8', text: 'But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.' },
  { ref: 'Romans 6:23', text: 'For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.' },
  { ref: 'Romans 10:9', text: 'If you declare with your mouth, Jesus is Lord, and believe in your heart that God raised him from the dead, you will be saved.' },
  { ref: 'Romans 12:12', text: 'Be joyful in hope, patient in affliction, faithful in prayer.' },
  { ref: '1 Corinthians 10:13', text: 'No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear.' },
  { ref: '1 Corinthians 15:58', text: 'Therefore, my dear brothers and sisters, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord, because you know that your labor in the Lord is not in vain.' },
  { ref: '2 Corinthians 4:17', text: 'For our light and momentary troubles are achieving for us an eternal glory that far outweighs them all.' },
  { ref: '2 Corinthians 5:7', text: 'For we live by faith, not by sight.' },
  { ref: '2 Corinthians 5:17', text: 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!' },
  { ref: '2 Corinthians 12:9', text: 'But he said to me, My grace is sufficient for you, for my power is made perfect in weakness.' },
  { ref: 'Galatians 2:20', text: 'I have been crucified with Christ and I no longer live, but Christ lives in me. The life I now live in the body, I live by faith in the Son of God, who loved me and gave himself for me.' },
  { ref: 'Galatians 6:9', text: 'Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.' },
  { ref: 'Ephesians 3:20', text: 'Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.' },
  { ref: 'Ephesians 4:32', text: 'Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.' },
  { ref: 'Philippians 4:4', text: 'Rejoice in the Lord always. I will say it again: Rejoice!' },
  { ref: 'Philippians 4:8', text: 'Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable — if anything is excellent or praiseworthy — think about such things.' },
  { ref: 'Colossians 3:2', text: 'Set your minds on things above, not on earthly things.' },
  { ref: 'Colossians 3:16', text: 'Let the message of Christ dwell among you richly as you teach and admonish one another with all wisdom through psalms, hymns, and songs from the Spirit, singing to God with gratitude in your hearts.' },
  { ref: '1 Thessalonians 5:16-18', text: 'Rejoice always, pray continually, give thanks in all circumstances; for this is God\'s will for you in Christ Jesus.' },
  { ref: '2 Thessalonians 3:3', text: 'But the Lord is faithful, and he will strengthen you and protect you from the evil one.' },
  { ref: '1 Timothy 6:6', text: 'But godliness with contentment is great gain.' },
  { ref: '2 Timothy 3:16-17', text: 'All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness, so that the servant of God may be thoroughly equipped for every good work.' },
  { ref: 'Hebrews 4:16', text: 'Let us then approach God\'s throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.' },
  { ref: 'Hebrews 12:1', text: 'Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles. And let us run with perseverance the race marked out for us.' },
  { ref: 'James 1:5', text: 'If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.' },
  { ref: 'James 4:7', text: 'Submit yourselves, then, to God. Resist the devil, and he will flee from you.' },
  { ref: '1 Peter 2:9', text: 'But you are a chosen people, a royal priesthood, a holy nation, God\'s special possession, that you may declare the praises of him who called you out of darkness into his wonderful light.' },
  { ref: '1 Peter 3:15', text: 'But in your hearts revere Christ as Lord. Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have.' },
  { ref: '1 John 1:9', text: 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.' },
  { ref: '1 John 4:8', text: 'Whoever does not love does not know God, because God is love.' },
  { ref: 'Revelation 3:20', text: 'Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and eat with that person, and they with me.' },
  { ref: 'Psalm 3:3', text: 'But you, Lord, are a shield around me, my glory, the One who lifts my head high.' },
  { ref: 'Psalm 4:8', text: 'In peace I will lie down and sleep, for you alone, Lord, make me dwell in safety.' },
  { ref: 'Psalm 5:3', text: 'In the morning, Lord, you hear my voice; in the morning I lay my requests before you and wait expectantly.' },
  { ref: 'Psalm 8:1', text: 'Lord, our Lord, how majestic is your name in all the earth! You have set your glory in the heavens.' },
  { ref: 'Psalm 9:9', text: 'The Lord is a refuge for the oppressed, a stronghold in times of trouble.' },
  { ref: 'Psalm 16:8', text: 'I keep my eyes always on the Lord. With him at my right hand, I will not be shaken.' },
  { ref: 'Psalm 18:2', text: 'The Lord is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge, my shield and the horn of my salvation, my stronghold.' },
  { ref: 'Psalm 19:1', text: 'The heavens declare the glory of God; the skies proclaim the work of his hands.' },
  { ref: 'Psalm 19:14', text: 'May these words of my mouth and this meditation of my heart be pleasing in your sight, Lord, my Rock and my Redeemer.' },
  { ref: 'Psalm 20:4', text: 'May he give you the desire of your heart and make all your plans succeed.' },
  { ref: 'Psalm 22:24', text: 'For he has not despised or scorned the suffering of the afflicted one; he has not hidden his face from him but has listened to his cry for help.' },
  { ref: 'Psalm 23:6', text: 'Surely your goodness and love will follow me all the days of my life, and I will dwell in the house of the Lord forever.' },
  { ref: 'Psalm 25:4-5', text: 'Show me your ways, Lord, teach me your paths. Guide me in your truth and teach me, for you are God my Savior, and my hope is in you all day long.' },
  { ref: 'Psalm 29:11', text: 'The Lord gives strength to his people; the Lord blesses his people with peace.' },
  { ref: 'Psalm 30:5', text: 'For his anger lasts only a moment, but his favor lasts a lifetime; weeping may stay for the night, but rejoicing comes in the morning.' },
  { ref: 'Psalm 31:24', text: 'Be strong and take heart, all you who hope in the Lord.' },
  { ref: 'Psalm 32:8', text: 'I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.' },
  { ref: 'Psalm 33:20-22', text: 'We wait in hope for the Lord; he is our help and our shield. In him our hearts rejoice, for we trust in his holy name. May your unfailing love be with us, Lord, even as we put our hope in you.' },
  { ref: 'Psalm 34:8', text: 'Taste and see that the Lord is good; blessed is the one who takes refuge in him.' },
  { ref: 'Psalm 34:18', text: 'The Lord is close to the brokenhearted and saves those who are crushed in spirit.' },
  { ref: 'Psalm 37:5', text: 'Commit your way to the Lord; trust in him and he will do this.' },
  { ref: 'Psalm 40:1-2', text: 'I waited patiently for the Lord; he turned to me and heard my cry. He lifted me out of the slimy pit, out of the mud and mire; he set my feet on a rock and gave me a firm place to stand.' },
  { ref: 'Psalm 42:5', text: 'Why, my soul, are you downcast? Why so disturbed within me? Put your hope in God, for I will yet praise him, my Savior and my God.' },
  { ref: 'Psalm 46:10', text: 'He says, Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.' },
  { ref: 'Psalm 51:10', text: 'Create in me a pure heart, O God, and renew a steadfast spirit within me.' },
  { ref: 'Psalm 55:22', text: 'Cast your cares on the Lord and he will sustain you; he will never let the righteous be shaken.' },
  { ref: 'Psalm 56:3', text: 'When I am afraid, I put my trust in you.' },
  { ref: 'Psalm 62:1-2', text: 'Truly my soul finds rest in God; my salvation comes from him. Truly he is my rock and my salvation; he is my fortress, I will never be shaken.' },
  { ref: 'Psalm 63:1', text: 'You, God, are my God, earnestly I seek you; I thirst for you, my whole being longs for you, in a dry and parched land where there is no water.' },
  { ref: 'Psalm 71:14', text: 'As for me, I will always have hope; I will praise you more and more.' },
  { ref: 'Psalm 73:26', text: 'My flesh and my heart may fail, but God is the strength of my heart and my portion forever.' },
  { ref: 'Psalm 84:11', text: 'For the Lord God is a sun and shield; the Lord bestows favor and honor; no good thing does he withhold from those whose walk is blameless.' },
  { ref: 'Psalm 86:5', text: 'You, Lord, are forgiving and good, abounding in love to all who call to you.' },
  { ref: 'Psalm 90:14', text: 'Satisfy us in the morning with your unfailing love, that we may sing for joy and be glad all our days.' },
  { ref: 'Psalm 91:11', text: 'For he will command his angels concerning you to guard you in all your ways.' },
  { ref: 'Psalm 94:19', text: 'When anxiety was great within me, your consolation brought me joy.' },
  { ref: 'Psalm 100:1-2', text: 'Shout for joy to the Lord, all the earth. Worship the Lord with gladness; come before him with joyful songs.' },
  { ref: 'Psalm 103:1-2', text: 'Praise the Lord, my soul; all my inmost being, praise his holy name. Praise the Lord, my soul, and forget not all his benefits.' },
  { ref: 'Psalm 103:12', text: 'As far as the east is from the west, so far has he removed our transgressions from us.' },
  { ref: 'Psalm 107:1', text: 'Give thanks to the Lord, for he is good; his love endures forever.' },
  { ref: 'Psalm 112:4', text: 'Even in darkness light dawns for the upright, for those who are gracious and compassionate and righteous.' },
  { ref: 'Psalm 116:1-2', text: 'I love the Lord, for he heard my voice; he heard my cry for mercy. Because he turned his ear to me, I will call on him as long as I live.' },
  { ref: 'Psalm 118:6', text: 'The Lord is with me; I will not be afraid. What can mere mortals do to me?' },
  { ref: 'Psalm 118:24', text: 'The Lord has done it this very day; let us rejoice today and be glad.' },
  { ref: 'Psalm 119:11', text: 'I have hidden your word in my heart that I might not sin against you.' },
  { ref: 'Psalm 119:165', text: 'Great peace have those who love your law, and nothing can make them stumble.' },
  { ref: 'Psalm 121:7-8', text: 'The Lord will keep you from all harm — he will watch over your life; the Lord will watch over your coming and going both now and forevermore.' },
  { ref: 'Psalm 126:5', text: 'Those who sow with tears will reap with songs of joy.' },
  { ref: 'Psalm 127:1', text: 'Unless the Lord builds the house, the builders labor in vain. Unless the Lord watches over the city, the guards stand watch in vain.' },
  { ref: 'Psalm 130:5', text: 'I wait for the Lord, my whole being waits, and in his word I put my hope.' },
  { ref: 'Psalm 133:1', text: 'How good and pleasant it is when God\'s people live together in unity!' },
  { ref: 'Psalm 138:3', text: 'When I called, you answered me; you greatly emboldened me.' },
  { ref: 'Psalm 139:23-24', text: 'Search me, God, and know my heart; test me and know my anxious thoughts. See if there is any offensive way in me, and lead me in the way everlasting.' },
  { ref: 'Psalm 143:8', text: 'Let the morning bring me word of your unfailing love, for I have put my trust in you. Show me the way I should go, for to you I entrust my life.' },
  { ref: 'Psalm 145:18', text: 'The Lord is near to all who call on him, to all who call on him in truth.' },
  { ref: 'Psalm 147:3', text: 'He heals the brokenhearted and binds up their wounds.' },
  { ref: 'Psalm 150:6', text: 'Let everything that has breath praise the Lord. Praise the Lord.' },
  { ref: 'Proverbs 10:12', text: 'Hatred stirs up conflict, but love covers over all wrongs.' },
  { ref: 'Proverbs 11:14', text: 'For lack of guidance a nation falls, but victory is won through many advisers.' },
  { ref: 'Proverbs 12:25', text: 'Anxiety weighs down the heart, but a kind word cheers it up.' },
  { ref: 'Proverbs 13:20', text: 'Walk with the wise and become wise, for a companion of fools suffers harm.' },
  { ref: 'Proverbs 14:29', text: 'Whoever is patient has great understanding, but one who is quick-tempered displays folly.' },
  { ref: 'Proverbs 15:1', text: 'A gentle answer turns away wrath, but a harsh word stirs up anger.' },
  { ref: 'Proverbs 16:3', text: 'Commit to the Lord whatever you do, and he will establish your plans.' },
  { ref: 'Proverbs 16:9', text: 'In their hearts humans plan their course, but the Lord establishes their steps.' },
  { ref: 'Proverbs 17:17', text: 'A friend loves at all times, and a brother is born for a time of adversity.' },
  { ref: 'Proverbs 18:10', text: 'The name of the Lord is a fortified tower; the righteous run to it and are safe.' },
  { ref: 'Proverbs 19:21', text: 'Many are the plans in a person\'s heart, but it is the Lord\'s purpose that prevails.' },
  { ref: 'Proverbs 20:7', text: 'The righteous lead blameless lives; blessed are their children after them.' },
  { ref: 'Proverbs 21:21', text: 'Whoever pursues righteousness and love finds life, prosperity and honor.' },
  { ref: 'Proverbs 23:18', text: 'There is surely a future hope for you, and your hope will not be cut off.' },
  { ref: 'Proverbs 24:16', text: 'For though the righteous fall seven times, they rise again, but the wicked stumble when calamity strikes.' },
  { ref: 'Proverbs 27:17', text: 'As iron sharpens iron, so one person sharpens another.' },
  { ref: 'Proverbs 28:13', text: 'Whoever conceals their sins does not prosper, but the one who confesses and renounces them finds mercy.' },
  { ref: 'Ecclesiastes 3:1', text: 'There is a time for everything, and a season for every activity under the heavens.' },
  { ref: 'Ecclesiastes 4:9-10', text: 'Two are better than one, because they have a good return for their labor: If either of them falls down, one can help the other up.' },
  { ref: 'Song of Solomon 8:7', text: 'Many waters cannot quench love; rivers cannot wash it away.' },
  { ref: 'Isaiah 1:18', text: 'Come now, let us settle the matter, says the Lord. Though your sins are like scarlet, they shall be as white as snow; though they are red as crimson, they shall be like wool.' },
  { ref: 'Isaiah 12:2', text: 'Surely God is my salvation; I will trust and not be afraid. The Lord, the Lord himself, is my strength and my defense; he has become my salvation.' },
  { ref: 'Isaiah 25:8', text: 'He will swallow up death forever. The Sovereign Lord will wipe away the tears from all faces.' },
  { ref: 'Isaiah 30:21', text: 'Whether you turn to the right or to the left, your ears will hear a voice behind you, saying, This is the way; walk in it.' },
  { ref: 'Isaiah 33:2', text: 'Lord, be gracious to us; we long for you. Be our strength every morning, our salvation in time of distress.' },
  { ref: 'Isaiah 40:8', text: 'The grass withers and the flowers fall, but the word of our God endures forever.' },
  { ref: 'Isaiah 40:29', text: 'He gives strength to the weary and increases the power of the weak.' },
  { ref: 'Isaiah 43:1', text: 'Do not fear, for I have redeemed you; I have summoned you by name; you are mine.' },
  { ref: 'Isaiah 43:2', text: 'When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you.' },
  { ref: 'Isaiah 46:4', text: 'Even to your old age and gray hairs I am he, I am he who will sustain you. I have made you and I will carry you; I will sustain you and I will rescue you.' },
  { ref: 'Isaiah 48:17', text: 'I am the Lord your God, who teaches you what is best for you, who directs you in the way you should go.' },
  { ref: 'Isaiah 53:5', text: 'But he was pierced for our transgressions, he was crushed for our iniquities; the punishment that brought us peace was on him, and by his wounds we are healed.' },
  { ref: 'Isaiah 54:10', text: 'Though the mountains be shaken and the hills be removed, yet my unfailing love for you will not be shaken nor my covenant of peace be removed, says the Lord, who has compassion on you.' },
  { ref: 'Isaiah 55:8-9', text: 'For my thoughts are not your thoughts, neither are your ways my ways, declares the Lord. As the heavens are higher than the earth, so are my ways higher than your ways and my thoughts than your thoughts.' },
  { ref: 'Isaiah 58:11', text: 'The Lord will guide you always; he will satisfy your needs in a sun-scorched land and will strengthen your frame. You will be like a well-watered garden, like a spring whose waters never fail.' },
  { ref: 'Isaiah 60:1', text: 'Arise, shine, for your light has come, and the glory of the Lord rises upon you.' },
  { ref: 'Isaiah 61:1', text: 'The Spirit of the Sovereign Lord is on me, because the Lord has anointed me to proclaim good news to the poor.' },
  { ref: 'Isaiah 65:24', text: 'Before they call I will answer; while they are still speaking I will hear.' },
  { ref: 'Jeremiah 17:7-8', text: 'But blessed is the one who trusts in the Lord, whose confidence is in him. They will be like a tree planted by the water that sends out its roots by the stream.' },
  { ref: 'Jeremiah 31:3', text: 'The Lord appeared to us in the past, saying: I have loved you with an everlasting love; I have drawn you with unfailing kindness.' },
  { ref: 'Jeremiah 33:3', text: 'Call to me and I will answer you and tell you great and unsearchable things you do not know.' },
  { ref: 'Ezekiel 36:26', text: 'I will give you a new heart and put a new spirit in you; I will remove from you your heart of stone and give you a heart of flesh.' },
  { ref: 'Daniel 6:22', text: 'My God sent his angel, and he shut the mouths of the lions. They have not hurt me, because I was found innocent in his sight.' },
  { ref: 'Hosea 6:3', text: 'Let us acknowledge the Lord; let us press on to acknowledge him. As surely as the sun rises, he will appear; he will come to us like the winter rains, like the spring rains that water the earth.' },
  { ref: 'Joel 2:25', text: 'I will repay you for the years the locusts have eaten.' },
  { ref: 'Nahum 1:7', text: 'The Lord is good, a refuge in times of trouble. He cares for those who trust in him.' },
  { ref: 'Habakkuk 3:19', text: 'The Sovereign Lord is my strength; he makes my feet like the feet of a deer, he enables me to tread on the heights.' },
  { ref: 'Malachi 3:10', text: 'Test me in this, says the Lord Almighty, and see if I will not throw open the floodgates of heaven and pour out so much blessing that there will not be room enough to store it.' },
  { ref: 'Luke 1:45', text: 'Blessed is she who has believed that the Lord would fulfill his promises to her!' },
  { ref: 'Luke 11:9', text: 'So I say to you: Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.' },
  { ref: 'Luke 12:7', text: 'Indeed, the very hairs of your head are all numbered. Don\'t be afraid; you are worth more than many sparrows.' },
  { ref: 'Luke 15:7', text: 'I tell you that in the same way there will be more rejoicing in heaven over one sinner who repents than over ninety-nine righteous persons who do not need to repent.' },
  { ref: 'Luke 18:27', text: 'What is impossible with man is possible with God.' },
  { ref: 'Luke 21:33', text: 'Heaven and earth will pass away, but my words will never pass away.' },
  { ref: 'John 3:17', text: 'For God did not send his Son into the world to condemn the world, but to save the world through him.' },
  { ref: 'John 6:35', text: 'Then Jesus declared, I am the bread of life. Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty.' },
  { ref: 'John 6:47', text: 'Very truly I tell you, the one who believes has eternal life.' },
  { ref: 'John 8:12', text: 'When Jesus spoke again to the people, he said, I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life.' },
  { ref: 'John 10:27-28', text: 'My sheep listen to my voice; I know them, and they follow me. I give them eternal life, and they shall never perish; no one will snatch them out of my hand.' },
  { ref: 'John 15:5', text: 'I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit; apart from me you can do nothing.' },
  { ref: 'John 15:7', text: 'If you remain in me and my words remain in you, ask whatever you wish, and it will be done for you.' },
  { ref: 'John 17:3', text: 'Now this is eternal life: that they know you, the only true God, and Jesus Christ, whom you have sent.' },
  { ref: 'Acts 2:21', text: 'And everyone who calls on the name of the Lord will be saved.' },
  { ref: 'Acts 4:12', text: 'Salvation is found in no one else, for there is no other name under heaven given to mankind by which we must be saved.' },
  { ref: 'Acts 16:31', text: 'Believe in the Lord Jesus, and you will be saved — you and your household.' },
  { ref: 'Romans 4:20-21', text: 'Yet he did not waver through unbelief regarding the promise of God, but was strengthened in his faith and gave glory to God, being fully persuaded that God had power to do what he had promised.' },
  { ref: 'Romans 8:1', text: 'Therefore, there is now no condemnation for those who are in Christ Jesus.' },
  { ref: 'Romans 8:11', text: 'And if the Spirit of him who raised Jesus from the dead is living in you, he who raised Christ from the dead will also give life to your mortal bodies because of his Spirit who lives in you.' },
  { ref: 'Romans 8:31', text: 'What, then, shall we say in response to these things? If God is for us, who can be against us?' },
  { ref: 'Romans 8:37', text: 'No, in all these things we are more than conquerors through him who loved us.' },
  { ref: 'Romans 12:9', text: 'Love must be sincere. Hate what is evil; cling to what is good.' },
  { ref: 'Romans 12:10', text: 'Be devoted to one another in love. Honor one another above yourselves.' },
  { ref: 'Romans 12:21', text: 'Do not be overcome by evil, but overcome evil with good.' },
  { ref: '1 Corinthians 2:9', text: 'What no eye has seen, what no ear has heard, and what no human mind has conceived — the things God has prepared for those who love him.' },
  { ref: '1 Corinthians 13:13', text: 'And now these three remain: faith, hope and love. But the greatest of these is love.' },
  { ref: '1 Corinthians 16:13-14', text: 'Be on your guard; stand firm in the faith; be courageous; be strong. Do everything in love.' },
  { ref: '2 Corinthians 1:3-4', text: 'Praise be to the God and Father of our Lord Jesus Christ, the Father of compassion and the God of all comfort, who comforts us in all our troubles.' },
  { ref: '2 Corinthians 3:17', text: 'Now the Lord is the Spirit, and where the Spirit of the Lord is, there is freedom.' },
  { ref: '2 Corinthians 9:8', text: 'And God is able to bless you abundantly, so that in all things at all times, having all that you need, you will abound in every good work.' },
  { ref: 'Galatians 3:26', text: 'So in Christ Jesus you are all children of God through faith.' },
  { ref: 'Galatians 5:1', text: 'It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.' },
  { ref: 'Ephesians 1:7', text: 'In him we have redemption through his blood, the forgiveness of sins, in accordance with the riches of God\'s grace.' },
  { ref: 'Ephesians 2:10', text: 'For we are God\'s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.' },
  { ref: 'Ephesians 3:17-18', text: 'And I pray that you, being rooted and established in love, may have power, together with all the Lord\'s holy people, to grasp how wide and long and high and deep is the love of Christ.' },
  { ref: 'Philippians 1:6', text: 'Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.' },
  { ref: 'Philippians 2:13', text: 'For it is God who works in you to will and to act in order to fulfill his good purpose.' },
  { ref: 'Philippians 3:14', text: 'I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.' },
  { ref: 'Colossians 1:17', text: 'He is before all things, and in him all things hold together.' },
  { ref: 'Colossians 2:6-7', text: 'So then, just as you received Christ Jesus as Lord, continue to live your lives in him, rooted and built up in him, strengthened in the faith as you were taught, and overflowing with thankfulness.' },
  { ref: '1 Thessalonians 4:17', text: 'And so we will be with the Lord forever.' },
  { ref: '1 Thessalonians 5:11', text: 'Therefore encourage one another and build each other up, just as in fact you are doing.' },
  { ref: '1 Timothy 4:8', text: 'For physical training is of some value, but godliness has value for all things, holding promise for both the present life and the life to come.' },
  { ref: '1 Timothy 6:12', text: 'Fight the good fight of the faith. Take hold of the eternal life to which you were called.' },
  { ref: 'Hebrews 10:23', text: 'Let us hold unswervingly to the hope we profess, for he who promised is faithful.' },
  { ref: 'Hebrews 12:2', text: 'Fixing our eyes on Jesus, the pioneer and perfecter of faith. For the joy set before him he endured the cross, scorning its shame, and sat down at the right hand of the throne of God.' },
  { ref: 'Hebrews 13:5', text: 'Never will I leave you; never will I forsake you.' },
  { ref: 'Hebrews 13:8', text: 'Jesus Christ is the same yesterday and today and forever.' },
  { ref: 'James 1:17', text: 'Every good and perfect gift is from above, coming down from the Father of the heavenly lights, who does not change like shifting shadows.' },
  { ref: 'James 2:17', text: 'In the same way, faith by itself, if it is not accompanied by action, is dead.' },
  { ref: 'James 4:8', text: 'Come near to God and he will come near to you.' },
  { ref: '1 Peter 1:3', text: 'Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope through the resurrection of Jesus Christ from the dead.' },
  { ref: '1 Peter 4:8', text: 'Above all, love each other deeply, because love covers over a multitude of sins.' },
  { ref: '1 Peter 5:10', text: 'And the God of all grace, who called you to his eternal glory in Christ, after you have suffered a little while, will himself restore you and make you strong, firm and steadfast.' },
  { ref: '2 Peter 1:3', text: 'His divine power has given us everything we need for a godly life through our knowledge of him who called us by his own glory and goodness.' },
  { ref: '1 John 2:17', text: 'The world and its desires pass away, but whoever does the will of God lives forever.' },
  { ref: '1 John 3:1', text: 'See what great love the Father has lavished on us, that we should be called children of God! And that is what we are!' },
  { ref: '1 John 4:4', text: 'You, dear children, are from God and have overcome them, because the one who is in you is greater than the one who is in the world.' },
  { ref: '1 John 5:14', text: 'This is the confidence we have in approaching God: that if we ask anything according to his will, he hears us.' },
  { ref: 'Jude 1:24', text: 'To him who is able to keep you from stumbling and to present you before his glorious presence without fault and with great joy.' },
  { ref: 'Revelation 1:8', text: 'I am the Alpha and the Omega, says the Lord God, who is, and who was, and who is to come, the Almighty.' },
  { ref: 'Revelation 3:5', text: 'The one who is victorious will, like them, be dressed in white. I will never blot out the name of that person from the book of life, but will acknowledge that name before my Father and his angels.' },
  { ref: 'Revelation 22:13', text: 'I am the Alpha and the Omega, the First and the Last, the Beginning and the End.' },
  { ref: 'Numbers 6:24-26', text: 'The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you; the Lord turn his face toward you and give you peace.' },
  { ref: 'Deuteronomy 6:5', text: 'Love the Lord your God with all your heart and with all your soul and with all your strength.' },
  { ref: 'Deuteronomy 31:6', text: 'Be strong and courageous. Do not be afraid or terrified because of them, for the Lord your God goes with you; he will never leave you nor forsake you.' },
  { ref: '1 Samuel 16:7', text: 'The Lord does not look at the things people look at. People look at the outward appearance, but the Lord looks at the heart.' },
  { ref: '2 Chronicles 7:14', text: 'If my people, who are called by my name, will humble themselves and pray and seek my face and turn from their wicked ways, then I will hear from heaven, and I will forgive their sin and will heal their land.' },
  { ref: 'Nehemiah 8:10', text: 'Do not grieve, for the joy of the Lord is your strength.' },
  { ref: 'Job 19:25', text: 'I know that my redeemer lives, and that in the end he will stand on the earth.' },
  { ref: 'Job 42:2', text: 'I know that you can do all things; no purpose of yours can be thwarted.' },
  { ref: 'Exodus 14:14', text: 'The Lord will fight for you; you need only to be still.' },
  { ref: 'Exodus 15:2', text: 'The Lord is my strength and my defense; he has become my salvation. He is my God, and I will praise him, my father\'s God, and I will exalt him.' },
  { ref: 'Leviticus 19:18', text: 'Love your neighbor as yourself. I am the Lord.' },
  { ref: 'Joshua 24:15', text: 'But as for me and my household, we will serve the Lord.' },
  { ref: 'Ruth 1:16', text: 'Where you go I will go, and where you stay I will stay. Your people will be my people and your God my God.' },
  { ref: '2 Samuel 22:31', text: 'As for God, his way is perfect: The Lord\'s word is flawless; he shields all who take refuge in him.' },
  { ref: '1 Kings 8:23', text: 'Lord, the God of Israel, there is no God like you in heaven above or on earth below — you who keep your covenant of love with your servants who continue wholeheartedly in your way.' },
  { ref: '1 Chronicles 16:34', text: 'Give thanks to the Lord, for he is good; his love endures forever.' },
  { ref: 'Ezra 8:22', text: 'The gracious hand of our God is on everyone who looks to him, but his great anger is against all who forsake him.' },
  { ref: 'Esther 4:14', text: 'And who knows but that you have come to your royal position for such a time as this?' },
  { ref: 'Matthew 6:34', text: 'Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own.' },
  { ref: 'Matthew 7:24', text: 'Therefore everyone who hears these words of mine and puts them into practice is like a wise man who built his house on the rock.' },
  { ref: 'Matthew 18:20', text: 'For where two or three gather in my name, there am I with them.' },
  { ref: 'Matthew 19:26', text: 'With man this is impossible, but with God all things are possible.' },
  { ref: 'Mark 9:23', text: 'Everything is possible for one who believes.' },
  { ref: 'Mark 10:27', text: 'With man this is impossible, but not with God; all things are possible with God.' },
  { ref: 'Mark 11:24', text: 'Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours.' },
  { ref: 'Luke 6:38', text: 'Give, and it will be given to you. A good measure, pressed down, shaken together and running over, will be poured into your lap.' },
  { ref: 'Luke 10:27', text: 'Love the Lord your God with all your heart and with all your soul and with all your strength and with all your mind; and love your neighbor as yourself.' },
  { ref: 'John 4:14', text: 'But whoever drinks the water I give them will never thirst. Indeed, the water I give them will become in them a spring of water welling up to eternal life.' },
  { ref: 'John 14:14', text: 'You may ask me for anything in my name, and I will do it.' },
  { ref: 'John 20:29', text: 'Then Jesus told him, Because you have seen me, you have believed; blessed are those who have not seen and yet have believed.' },
  { ref: 'Acts 20:35', text: 'It is more blessed to give than to receive.' },
  { ref: 'Romans 12:1', text: 'Therefore, I urge you, brothers and sisters, in view of God\'s mercy, to offer your bodies as a living sacrifice, holy and pleasing to God — this is your true and proper worship.' },
  { ref: 'Romans 14:8', text: 'If we live, we live for the Lord; and if we die, we die for the Lord. So, whether we live or die, we belong to the Lord.' },
  { ref: '1 Corinthians 3:16', text: 'Don\'t you know that you yourselves are God\'s temple and that God\'s Spirit dwells in your midst?' },
  { ref: '1 Corinthians 6:19-20', text: 'Do you not know that your bodies are temples of the Holy Spirit, who is in you, whom you have received from God? You are not your own; you were bought at a price.' },
  { ref: '2 Corinthians 4:7', text: 'But we have this treasure in jars of clay to show that this all-surpassing power is from God and not from us.' },
  { ref: '2 Corinthians 8:9', text: 'For you know the grace of our Lord Jesus Christ, that though he was rich, yet for your sake he became poor, so that you through his poverty might become rich.' },
  { ref: 'Galatians 6:2', text: 'Carry each other\'s burdens, and in this way you will fulfill the law of Christ.' },
  { ref: 'Ephesians 5:1-2', text: 'Follow God\'s example, therefore, as dearly loved children and walk in the way of love, just as Christ loved us and gave himself up for us as a fragrant offering and sacrifice to God.' },
  { ref: 'Ephesians 6:18', text: 'And pray in the Spirit on all occasions with all kinds of prayers and requests. With this in mind, be alert and always keep on praying for all the Lord\'s people.' },
  { ref: 'Philippians 4:11', text: 'I have learned, in whatsoever state I am, therewith to be content.' },
  { ref: 'Colossians 4:2', text: 'Devote yourselves to prayer, being watchful and thankful.' },
  { ref: '2 Timothy 4:7', text: 'I have fought the good fight, I have finished the race, I have kept the faith.' },
  { ref: 'Titus 3:5', text: 'He saved us, not because of righteous things we had done, but because of his mercy.' },
  { ref: 'Hebrews 6:19', text: 'We have this hope as an anchor for the soul, firm and secure.' },
  { ref: 'James 5:16', text: 'The prayer of a righteous person is powerful and effective.' },
  { ref: '1 Peter 1:8', text: 'Though you have not seen him, you love him; and even though you do not see him now, you believe in him and are filled with an inexpressible and glorious joy.' },
  { ref: '2 Peter 3:9', text: 'The Lord is not slow in keeping his promise, as some understand slowness. Instead he is patient with you, not wanting anyone to perish, but everyone to come to repentance.' },
  { ref: 'Revelation 7:17', text: 'For the Lamb at the center of the throne will be their shepherd; he will lead them to springs of living water. And God will wipe away every tear from their eyes.' },
  { ref: 'Revelation 21:3', text: 'And I heard a loud voice from the throne saying, Look! God\'s dwelling place is now among the people, and he will dwell with them.' },
  { ref: 'Revelation 22:20', text: 'He who testifies to these things says, Yes, I am coming soon. Amen. Come, Lord Jesus.' },
]

export function getRandomVerse(): Verse {
  return VERSES[Math.floor(Math.random() * VERSES.length)]
}

export function getDailyVerse(): Verse {
  const start = new Date('2024-01-01').getTime()
  const today = new Date().setHours(0, 0, 0, 0)
  const dayIndex = Math.floor((today - start) / 86400000)
  return VERSES[dayIndex % VERSES.length]
}
